#%RAML 1.0
title: ILL Connector
version: v1.0
protocols: [ HTTP, HTTPS ]
baseUri: http://localhost:9130

documentation:
  - title: Interlibrary Loan Connector
    content: <b>API for interlibrary loan connector</b>

types:
  errors:     !include raml-util/schemas/errors.schema
  actionRequest: !include schemas/action-request.schema
  actionResponse: !include mod-ill-ramls/schemas/sa-request/response/request-confirmation.schema
  searchResponse: !include mod-ill-ramls/schemas/search/search-response.schema

traits:
  language: !include raml-util/traits/language.raml
  pageable: !include raml-util/traits/pageable.raml
  searchable: !include raml-util/traits/searchable.raml
  validate: !include raml-util/traits/validation.raml

/ill-connector:
  /search:
    get:
      is: [
        pageable,
        searchable: {description: "searchable using CQL", example: "title=\"The Mandalorian\""},
      ]
      displayName: Perform a search on the supplying agency
      responses:
        200:
          description: Returns search results
          body:
            application/json:
              type: searchResponse
              example:
                strict: false
                value: !include mod-ill-ramls/examples/search/search-response.json
  /action:
    post:
      displayName: Perform an action on a request
      body:
        application/json:
          type: actionRequest
          examples:
            ex: !include examples/action-request.json
      responses:
        200:
          description: Returns success body for updated request
          body:
            application/json:
              type: actionResponse
              example:
                strict: false
                value: !include mod-ill-ramls/examples/sa-request/response/request-confirmation.json
        201:
          description: Returns success body for created request
          body:
            application/json:
              type: actionResponse
              example:
                strict: false
                value: !include mod-ill-ramls/examples/sa-request/response/request-confirmation.json
        500:
          description: Returns error body for failed action
          body:
            application/json:
              type: actionResponse
              example:
                strict: false
                value: !include mod-ill-ramls/examples/sa-request/response/request-confirmation.json
  /sa-update:
    post:
      displayName: Receive an orderline update from the BL
      description: See https://apitest.bldss.bl.uk/docs/guide/single.html#orderlineUpdates
      body:
        application/xml:
          type: string
          example: !include examples/sa-update.xml
      responses:
        200:
          description: Successful receipt of update message
          body:
            application/xml:
              type: string
              example: !include examples/sa-update-response.xml
